[env:nano_33_iot]
platform = atmelsam@8.3.0
board = nano_33_iot
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
lib_deps = adafruit/Adafruit INA219@1.2.3
[platformio]
src_dir = firmware
